import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { BrainCircuit, Sparkles, FileText, BarChart3, ArrowRight, Zap, Shield, Star, Globe, Cpu, Target } from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import Iridescence from '../components/Iridescence';

/* ── Data ──────────────────────────────────────────────────────────────── */
const FEATURES = [
  {
    icon: FileText,
    title: 'Resume-Aware Questions',
    desc: 'Upload your resume and get interview questions tailored to your actual experience and skills.',
  },
  {
    icon: BrainCircuit,
    title: 'AI-Powered Generation',
    desc: 'Questions generated by cutting-edge LLMs — covering technical, behavioral, situational & more.',
  },
  {
    icon: BarChart3,
    title: 'Instant Feedback & Scores',
    desc: 'Get detailed AI feedback, per-question scores, and overall performance analysis after each session.',
  },
];

const STATS = [
  { value: '10K+', label: 'Questions Generated' },
  { value: '98%', label: 'User Satisfaction' },
  { value: '< 3s', label: 'Response Time' },
  { value: 'Free', label: 'To Get Started' },
];

const STEPS = [
  { num: '01', title: 'Create Account', desc: 'Sign up in seconds — no credit card required.', icon: Zap },
  { num: '02', title: 'Set Up Interview', desc: 'Enter job description, select experience level & question types.', icon: Target },
  { num: '03', title: 'Practice & Improve', desc: 'Answer questions and get AI-powered feedback instantly.', icon: Star },
];

const TECH = [
  { name: 'RAG Pipeline', icon: Cpu },
  { name: 'Semantic Search', icon: Globe },
  { name: 'Groq Inference', icon: Zap },
  { name: 'Resume Parsing', icon: FileText },
];

/* ── Animations ────────────────────────────────────────────────────────── */
const stagger = { hidden: {}, visible: { transition: { staggerChildren: 0.12 } } };
const fadeUp = {
  hidden: { opacity: 0, y: 40 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] } },
};

/* ── Reusable Glass Card ───────────────────────────────────────────────── */
function Glass({ children, className = '', glow = false }) {
  return (
    <div className={`relative overflow-hidden rounded-3xl
      bg-white/[0.04] backdrop-blur-xl
      border border-white/[0.08]
      ${glow ? 'shadow-[0_0_60px_rgba(199,58,130,0.08)]' : ''}
      ${className}`}
    >
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />
      {children}
    </div>
  );
}

/* ── Gradient Button ───────────────────────────────────────────────────── */
function GradientBtn({ to, children, large = false }) {
  return (
    <Link to={to}
      className={`group relative inline-flex items-center gap-3 rounded-2xl font-semibold text-white overflow-hidden
        ${large ? 'px-10 py-4 text-base' : 'px-7 py-3 text-sm'}
        shadow-[0_0_30px_rgba(199,58,130,0.25)] hover:shadow-[0_0_50px_rgba(199,58,130,0.45)]
        transition-shadow duration-500`}
    >
      {/* Animated gradient fill */}
      <div className="absolute inset-0 bg-gradient-to-r from-rose-600 via-pink-600 to-fuchsia-600
                      bg-[length:200%_100%] animate-shimmer" />
      {/* Top inner highlight */}
      <div className="absolute inset-0 shadow-[inset_0_1px_0_rgba(255,255,255,0.25)]" />
      <span className="relative z-10 flex items-center gap-2">{children}</span>
    </Link>
  );
}

/* ── Ghost Button ──────────────────────────────────────────────────────── */
function GhostBtn({ to, children, large = false }) {
  return (
    <Link to={to}
      className={`inline-flex items-center gap-2 rounded-2xl font-semibold
        bg-white/[0.04] backdrop-blur-xl border border-white/[0.1]
        text-slate-300 hover:text-white hover:bg-white/[0.08] hover:border-white/[0.18]
        transition-all duration-300
        ${large ? 'px-10 py-4 text-base' : 'px-7 py-3 text-sm'}`}
    >
      {children}
    </Link>
  );
}

/* ══════════════════════════════════════════════════════════════════════════
    MAIN COMPONENT
══════════════════════════════════════════════════════════════════════════ */
export default function LandingPage() {
  const { isAuthenticated } = useAuthStore();

  return (
    <div className="relative min-h-screen overflow-x-hidden">

      {/* ── FULL-PAGE IRIDESCENCE ─────────────────────────────────────
          Stays fixed behind everything, visible through all sections
      ──────────────────────────────────────────────────────────────── */}
      <div className="fixed inset-0 z-0">
        <Iridescence
          color={[0.792156862745098, 0.14901960784313725, 0.3137254901960784]}
          mouseReact
          amplitude={0.1}
          speed={1}
        />
      </div>

      {/* ── Content wrapper — sits above iridescence ────────────────── */}
      <div className="relative z-10">

        {/* ═══════════════════════════════════════════════════════════════
            NAVBAR — Floating frosted glass
        ═══════════════════════════════════════════════════════════════ */}
        <motion.nav
          initial={{ y: -80, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          className="fixed top-4 left-1/2 -translate-x-1/2 w-[92%] max-w-5xl z-50
                     bg-white/[0.05] backdrop-blur-2xl border border-white/[0.07]
                     rounded-2xl shadow-[0_8px_40px_rgba(0,0,0,0.5)]"
        >
          <div className="px-6 h-14 flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2.5 group">
              <div className="p-1.5 bg-gradient-to-br from-rose-500 to-pink-600 rounded-xl
                              shadow-[0_0_16px_rgba(244,63,94,0.4)]
                              group-hover:shadow-[0_0_24px_rgba(244,63,94,0.6)] transition-shadow">
                <BrainCircuit className="w-5 h-5 text-white" />
              </div>
              <span className="font-display font-bold text-lg text-white tracking-tight">
                Interview<span className="text-rose-400">AI</span>
              </span>
            </Link>

            <div className="flex items-center gap-3">
              {isAuthenticated ? (
                <GradientBtn to="/dashboard">Dashboard <ArrowRight className="w-4 h-4" /></GradientBtn>
              ) : (
                <>
                  <Link to="/login" className="hidden sm:inline-flex px-4 py-2 rounded-xl text-sm font-medium
                    text-slate-300 hover:text-white hover:bg-white/[0.06] transition-all">
                    Sign In
                  </Link>
                  <GradientBtn to="/register">Get Started <Sparkles className="w-3.5 h-3.5" /></GradientBtn>
                </>
              )}
            </div>
          </div>
        </motion.nav>

        {/* ═══════════════════════════════════════════════════════════════
            HERO — Full viewport, transparent so iridescence shows
        ═══════════════════════════════════════════════════════════════ */}
        <section className="relative min-h-screen flex items-center justify-center px-6">
          {/* Soft vignette — no hard edges */}
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_60%_at_50%_40%,transparent_40%,rgba(15,15,26,0.5)_100%)]" />

          <div className="max-w-5xl mx-auto text-center relative z-10 pt-20">
            <motion.div variants={stagger} initial="hidden" animate="visible">

              {/* Pill badge */}
              <motion.div variants={fadeUp} className="mb-8 inline-flex">
                <span className="inline-flex items-center gap-2.5 px-5 py-2 rounded-full text-xs font-semibold tracking-wide
                                bg-rose-500/10 backdrop-blur-xl border border-rose-400/20 text-rose-300
                                shadow-[0_0_20px_rgba(244,63,94,0.1)]">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute h-full w-full rounded-full bg-rose-400 opacity-60" />
                    <span className="relative rounded-full h-2 w-2 bg-rose-400" />
                  </span>
                  AI + RAG Pipeline — Fully Free
                </span>
              </motion.div>

              {/* Headline */}
              <motion.h1 variants={fadeUp}
                className="text-5xl sm:text-7xl lg:text-8xl font-display font-extrabold text-white leading-[0.92] mb-8 tracking-tight"
              >
                Ace Every
                <br />
                <span className="relative inline-block mt-2">
                  <span className="bg-gradient-to-r from-rose-300 via-pink-300 to-fuchsia-300 bg-clip-text text-transparent">
                    Interview
                  </span>
                  <motion.span
                    initial={{ scaleX: 0 }}
                    animate={{ scaleX: 1 }}
                    transition={{ delay: 0.9, duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
                    className="absolute -bottom-2 left-0 right-0 h-1 bg-gradient-to-r from-rose-500 to-fuchsia-500 rounded-full origin-left"
                  />
                </span>
              </motion.h1>

              {/* Sub */}
              <motion.p variants={fadeUp}
                className="text-lg sm:text-xl text-white/60 max-w-2xl mx-auto mb-12 leading-relaxed font-light"
              >
                Upload your resume, paste a job description — AI generates{' '}
                <span className="text-white font-medium">personalized interview questions</span>{' '}
                with instant scoring & feedback.
              </motion.p>

              {/* CTAs */}
              <motion.div variants={fadeUp} className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-8">
                <GradientBtn to="/register" large>
                  Start Practicing Free <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                </GradientBtn>
                <GhostBtn to="/login" large>Sign In</GhostBtn>
              </motion.div>

              {/* Trust */}
              <motion.div variants={fadeUp} className="flex items-center justify-center gap-4 flex-wrap text-sm text-white/30">
                <span className="flex items-center gap-1.5"><Shield className="w-3.5 h-3.5 text-emerald-400" /> No credit card</span>
                <span className="w-1 h-1 rounded-full bg-white/10" />
                <span className="flex items-center gap-1.5"><Zap className="w-3.5 h-3.5 text-amber-400" /> Instant setup</span>
                <span className="w-1 h-1 rounded-full bg-white/10" />
                <span className="flex items-center gap-1.5"><Star className="w-3.5 h-3.5 text-rose-400" /> Open-source AI</span>
              </motion.div>
            </motion.div>
          </div>

          {/* Scroll indicator */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.8 }}
            className="absolute bottom-10 left-1/2 -translate-x-1/2"
          >
            <motion.div
              animate={{ y: [0, 8, 0] }}
              transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
              className="w-6 h-10 rounded-full border-2 border-white/15 flex items-start justify-center p-1.5"
            >
              <div className="w-1.5 h-2.5 rounded-full bg-white/30" />
            </motion.div>
          </motion.div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            STATS — Floating glass bar
        ═══════════════════════════════════════════════════════════════ */}
        <section className="relative z-10 -mt-10 px-6 pb-24">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <Glass className="max-w-4xl mx-auto" glow>
              <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-white/[0.05]">
                {STATS.map(({ value, label }, i) => (
                  <motion.div key={label}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: i * 0.1 }}
                    className="px-6 py-8 text-center"
                  >
                    <div className="text-3xl sm:text-4xl font-display font-bold
                                    bg-gradient-to-r from-rose-400 to-fuchsia-400 bg-clip-text text-transparent mb-1">
                      {value}
                    </div>
                    <div className="text-sm text-white/40">{label}</div>
                  </motion.div>
                ))}
              </div>
            </Glass>
          </motion.div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            FEATURES — Glass cards, rose-pink palette
        ═══════════════════════════════════════════════════════════════ */}
        <section className="py-24 px-6 relative">
          <div className="max-w-5xl mx-auto relative z-10">
            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              className="text-center mb-16"
            >
              <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold
                              bg-rose-500/10 text-rose-300 border border-rose-400/20 mb-6">
                <Sparkles className="w-3 h-3" /> Features
              </span>
              <h2 className="text-4xl sm:text-5xl font-display font-bold text-white mb-5 tracking-tight">
                Everything you need to
                <br />
                <span className="bg-gradient-to-r from-rose-300 to-fuchsia-300 bg-clip-text text-transparent">
                  prepare & succeed
                </span>
              </h2>
              <p className="text-white/40 max-w-xl mx-auto text-lg">
                A complete AI interview prep platform, built for modern job seekers.
              </p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {FEATURES.map(({ icon: Icon, title, desc }, i) => (
                <motion.div key={title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.15 }}
                >
                  <Glass className="p-8 group h-full hover:border-rose-500/20
                    hover:shadow-[0_0_50px_rgba(199,58,130,0.1)] transition-all duration-500">
                    <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-rose-500 to-pink-600
                                    flex items-center justify-center mb-6 shadow-lg
                                    group-hover:scale-110 group-hover:shadow-[0_0_30px_rgba(244,63,94,0.3)]
                                    transition-all duration-300">
                      <Icon className="w-7 h-7 text-white" />
                    </div>
                    <h3 className="text-xl font-semibold text-white mb-3">{title}</h3>
                    <p className="text-white/40 text-sm leading-relaxed">{desc}</p>
                    <div className="mt-6 h-0.5 w-0 group-hover:w-full bg-gradient-to-r from-rose-500 to-fuchsia-500 rounded-full transition-all duration-700" />
                  </Glass>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            HOW IT WORKS — Timeline steps
        ═══════════════════════════════════════════════════════════════ */}
        <section className="py-24 px-6">
          <div className="max-w-4xl mx-auto">
            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              className="text-center mb-16"
            >
              <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold
                              bg-fuchsia-500/10 text-fuchsia-300 border border-fuchsia-400/20 mb-6">
                <Target className="w-3 h-3" /> How It Works
              </span>
              <h2 className="text-4xl sm:text-5xl font-display font-bold text-white mb-5 tracking-tight">
                From zero to
                <br />
                <span className="bg-gradient-to-r from-pink-300 to-rose-300 bg-clip-text text-transparent">
                  interview-ready
                </span>
              </h2>
              <p className="text-white/40 text-lg">Three simple steps to supercharge your practice</p>
            </motion.div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
              {/* Connecting line */}
              <div className="hidden md:block absolute top-[3.5rem] left-[18%] right-[18%] h-px
                              bg-gradient-to-r from-rose-500/30 via-pink-500/40 to-fuchsia-500/30" />

              {STEPS.map(({ num, title, desc, icon: StepIcon }, i) => (
                <motion.div key={num}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.2 }}
                  className="text-center relative"
                >
                  <div className="relative inline-flex mb-6">
                    <Glass className="w-20 h-20 !rounded-3xl flex items-center justify-center
                      shadow-[0_0_30px_rgba(199,58,130,0.12)]">
                      <StepIcon className="w-8 h-8 text-rose-300" />
                    </Glass>
                    <span className="absolute -top-2 -right-2 w-7 h-7 rounded-full
                                     bg-gradient-to-br from-rose-500 to-pink-600
                                     flex items-center justify-center text-xs font-bold text-white
                                     shadow-[0_0_12px_rgba(244,63,94,0.4)]">
                      {num}
                    </span>
                  </div>
                  <h3 className="text-xl font-semibold text-white mb-2">{title}</h3>
                  <p className="text-white/40 text-sm leading-relaxed max-w-xs mx-auto">{desc}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            TECH STRIP
        ═══════════════════════════════════════════════════════════════ */}
        <section className="py-10 px-6 border-y border-white/[0.04]">
          <div className="max-w-4xl mx-auto flex flex-wrap items-center justify-center gap-4">
            <span className="text-[11px] text-white/25 uppercase tracking-[0.2em] font-semibold mr-2">Built with</span>
            {TECH.map(({ name, icon: TechIcon }) => (
              <span key={name} className="inline-flex items-center gap-2 px-4 py-2 rounded-full
                bg-white/[0.03] border border-white/[0.06] text-white/35 text-sm
                hover:text-rose-300 hover:border-rose-500/20 hover:bg-rose-500/5
                transition-all duration-300 cursor-default">
                <TechIcon className="w-3.5 h-3.5" />
                {name}
              </span>
            ))}
          </div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            FINAL CTA — Big glass card
        ═══════════════════════════════════════════════════════════════ */}
        <section className="py-28 px-6">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-3xl mx-auto"
          >
            <Glass className="p-12 sm:p-16 text-center" glow>
              <motion.div
                animate={{ rotate: [0, 5, -5, 0] }}
                transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut' }}
                className="inline-flex mb-8"
              >
                <div className="w-16 h-16 rounded-3xl bg-gradient-to-br from-rose-500 to-pink-600
                                flex items-center justify-center
                                shadow-[0_0_40px_rgba(244,63,94,0.35)]">
                  <BrainCircuit className="w-8 h-8 text-white" />
                </div>
              </motion.div>

              <h2 className="text-4xl sm:text-5xl font-display font-bold text-white mb-5 tracking-tight">
                Ready to nail your
                <br />
                <span className="bg-gradient-to-r from-rose-300 to-fuchsia-300 bg-clip-text text-transparent">
                  next interview?
                </span>
              </h2>
              <p className="text-white/40 mb-10 text-lg max-w-lg mx-auto">
                Join thousands of candidates using AI to prepare smarter, not harder.
              </p>

              <GradientBtn to="/register" large>
                Get Started — It's Free <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </GradientBtn>
            </Glass>
          </motion.div>
        </section>

        {/* ═══════════════════════════════════════════════════════════════
            FOOTER
        ═══════════════════════════════════════════════════════════════ */}
        <footer className="border-t border-white/[0.04] py-8 px-6">
          <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
            <Link to="/" className="flex items-center gap-2 group">
              <BrainCircuit className="w-5 h-5 text-rose-400 group-hover:text-rose-300 transition-colors" />
              <span className="font-display font-semibold text-white">
                Interview<span className="text-rose-400">AI</span>
              </span>
            </Link>
            <p className="text-white/25 text-sm">© 2026 InterviewAI · Built with MERN + Groq AI</p>
          </div>
        </footer>

      </div>{/* end content wrapper */}
    </div>
  );
}
